version: '2'
services:
  bitmark-node:
    environment:
      - EC2_IPV4=127.0.0.1
      - BTC_ADDR=1KtkRmq3iAjxevKX8sYTSxU8AdRhrYGAPy
      - LTC_ADDR=LN4jSR7ybzcSR9J2xv76TcmTqW3Mo6NgTj
    build: .
    ports:
     - "0.0.0.0:2130:2130"
     - "0.0.0.0:2135:2135"
     - "0.0.0.0:2136:2136"
     - "0.0.0.0:2150:2150"
     - "0.0.0.0:8080:9980"
